// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9Iw4S7EnfyhbOd8mNAfL7B18630yFos',
    appId: '1:708909213706:web:703bc6c9a4a17213f617f3',
    messagingSenderId: '708909213706',
    projectId: 'culturize-b5350',
    authDomain: 'culturize-b5350.firebaseapp.com',
    storageBucket: 'culturize-b5350.appspot.com',
    measurementId: 'G-865FB6DQ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcVLMGhe0sitWkhBnPAHmIH7sooKABJlY',
    appId: '1:708909213706:android:b5dbfd231c491c94f617f3',
    messagingSenderId: '708909213706',
    projectId: 'culturize-b5350',
    storageBucket: 'culturize-b5350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zBmVtq28K7bWiA1pScAWM8POUiejgHg',
    appId: '1:708909213706:ios:726cdcc01d9d3367f617f3',
    messagingSenderId: '708909213706',
    projectId: 'culturize-b5350',
    storageBucket: 'culturize-b5350.appspot.com',
    iosClientId: '708909213706-1kqi4nokt7snkq5dg8al0auvg1up73es.apps.googleusercontent.com',
    iosBundleId: 'com.example.culturize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zBmVtq28K7bWiA1pScAWM8POUiejgHg',
    appId: '1:708909213706:ios:726cdcc01d9d3367f617f3',
    messagingSenderId: '708909213706',
    projectId: 'culturize-b5350',
    storageBucket: 'culturize-b5350.appspot.com',
    iosClientId: '708909213706-1kqi4nokt7snkq5dg8al0auvg1up73es.apps.googleusercontent.com',
    iosBundleId: 'com.example.culturize',
  );
}
